export const FETCH_GET_ATTACKS_REQUEST = "FETCH_GET_ATTACKS_REQUEST";
export const FETCH_GET_ATTACKS_SUCCESS = "FETCH_GET_ATTACKS_SUCCESS";
export const FETCH_GET_ATTACKS_FAILURE = "FETCH_GET_ATTACKS_FAILURE";
